# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-10 18:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='portfolio_site',
            new_name='portofolio_site',
        ),
    ]
